url: https://mexatur.github.io/
locale: "en-US"
title: "Mehmet Akif Turhan"
description: >
  I'm a Web - Application Developer.
keywords:
  - Mehmet Akif Turhan
  - web developer
  - software engineer
  - application developer
social:
  name: "Mehmet Akif Turhan"
  links:
    - https://www.linkedin.com/in/mexatur
    - https://github.com/mexatur

author:
  name: Mehmet Akif Turhan
  email: Akifturhan89@gmail.com
  type: person
  job_title: Web - Application Developer

share_image: /android-chrome-512x512.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 20
paginate_path: /blog/:num
show_excerpts: true
google_analytics: G-ZPHHT8GE5Z
future: true

sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      lang: tr-TR
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      lang: en-US

navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Resume
    url: /cv/

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
